# Generated by Django 3.0.3 on 2020-02-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSystemDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='BSName')),
            ],
        ),
        migrations.CreateModel(
            name='PriorityDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('ru_name', models.CharField(blank=True, max_length=10, verbose_name='ru_name')),
            ],
        ),
    ]
