# Generated by Django 3.0.3 on 2020-02-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0003_auto_20200209_0032'),
        ('requestmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('ru_name', models.CharField(blank=True, max_length=10, verbose_name='ru_name')),
            ],
        ),
        migrations.CreateModel(
            name='PositionDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('ru_name', models.CharField(blank=True, max_length=10, verbose_name='ru_name')),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatusDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('ru_name', models.CharField(blank=True, max_length=10, verbose_name='ru_name')),
            ],
        ),
        migrations.CreateModel(
            name='SDRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_info', models.CharField(blank=True, max_length=128, verbose_name='pc_info')),
                ('theme', models.CharField(blank=True, max_length=128, verbose_name='theme')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('bs_system', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bs_system', to='requestmanager.BusinessSystemDictionary')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='usermanager.Profile')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='requestmanager.LocationDictionary')),
                ('position', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='requestmanager.PositionDictionary')),
                ('priority', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority', to='requestmanager.PriorityDictionary')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='usermanager.Profile')),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='requestmanager.RequestStatusDictionary')),
            ],
        ),
    ]
