# Generated by Django 3.0.3 on 2020-02-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmanager', '0002_locationdictionary_positiondictionary_requeststatusdictionary_sdrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdrequest',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdrequest',
            name='ip_adress',
            field=models.CharField(blank=True, max_length=20, verbose_name='ip_adress'),
        ),
    ]
