# Generated by Django 3.0.3 on 2020-02-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0004_locationdictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdictionary',
            name='ru_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='ru_name'),
        ),
    ]
