# Generated by Django 3.0.3 on 2020-02-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0005_departmentdictionary_ru_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdictionary',
            name='ru_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='ru_name'),
        ),
        migrations.AlterField(
            model_name='locationdictionary',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='locationdictionary',
            name='ru_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='ru_name'),
        ),
    ]
